version: "3.1"

services:
  tg-bot-postgres:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

  bot:
    build: ./
    container_name: TgTagBot
    depends_on:
      - tg-bot-postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: tg-bot-postgres
    volumes:
      - ./migrations:/usr/app/migrations


volumes:
  postgres_volume: